<?php


namespace app\admin\controller;

class AdminAuthBase extends AdminBase
{
    public $userId = 0;
    public $username = '';
    public $authorization = '';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->authorization = $this->request->header('Authorization');
        if (!$this->authorization || !$this->isLogin()) {
            return $this->show(config('status.not_login'), '用户未登录');
        }
    }
    
    public function isLogin()
    {
        $userInfo = cache(config('admin.admin_token_pre').$this->authorization);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['uid']) && !empty($userInfo['username'])) {
            $this->username = $userInfo['username'];
            $this->userId = $userInfo['uid'];
            return true;
        }
        return false;
    }
}
